/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package infomart;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.text.SimpleDateFormat;

/**
 *
 * @author Actmiz
 */
public class JF_Project_Akhir extends javax.swing.JFrame {

    /**
     * Creates new form JF_Project_Akhir
     */
    String tanggal;
    private DefaultTableModel model;

    public void totalbiaya() {
        int jumlahBaris = jTable1.getRowCount();
        int totalBiaya = 0;
        int jumlahBarang, hargaBarang;
        for (int i = 0; i < jumlahBaris; i++) {
            jumlahBarang = Integer.parseInt(jTable1.getValueAt(i, 4).toString());
            hargaBarang = Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            totalBiaya = totalBiaya + (jumlahBarang * hargaBarang);
        }
        TotalPembayaran.setText(String.valueOf(totalBiaya));
        Total.setText("RP" + totalBiaya + ",00");
    }

    private void autonumber() {
        String No_Transaksi = "IF000";
        int i = 0;
        try {
            Connection c = koneksi.getkonesi();
            Statement s = c.createStatement();
            String sql = "SELECT NoFaktur FROM penjualan";
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                No_Transaksi = r.getString("NoFaktur");
            }
            No_Transaksi = No_Transaksi.substring(4);
            i = Integer.parseInt(No_Transaksi) + 1;
            No_Transaksi = "00" + i;
            No_Transaksi = "IF" + No_Transaksi.substring(No_Transaksi.length() - 3);
            txtNo_Transaksi.setText(No_Transaksi);
        } catch (Exception e) {
            // TODO: handle exception
        }
    }

    public void loadData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {
                txtNo_Transaksi.getText(),
                IdBarang.getText(),
                Nama_Barang.getText(),
                Harga.getText(),
                Qty.getText(),
                TotalPembayaran.getText()
        });
    }

    public void kosong() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    }

    public void utama() {
        txtNo_Transaksi.setText("");
        IdBarang.setText("");
        Nama_Barang.setText("");
        Harga.setText("");
        Qty.setText("");
        autonumber();
    }

    public void hapus() {
        ID_Customer.setText("");
        Customer.setText("");
        TotalPembayaran.setText("");
        Pembayaran.setText("");
        Kembalian.setText("");
        Total.setText("");
    }

    public void hapus2() {
        IdBarang.setText("");
        Nama_Barang.setText("");
        Harga.setText("");
        Qty.setText("");
    }

    public void add() {
        int qty, harga, total;
        qty = Integer.valueOf(Qty.getText());
        harga = Integer.valueOf(Harga.getText());
        total = qty * harga;
        TotalPembayaran.setText(String.valueOf(total));

        loadData();
        totalbiaya();
        hapus2();
        IdBarang.requestFocus();
    }

    public JF_Project_Akhir() {
        initComponents();

        model = new DefaultTableModel();

        jTable1.setModel(model);

        model.addColumn("No Transaksi");
        model.addColumn("ID Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga");
        model.addColumn("Qty");
        model.addColumn("Total");

        Date date = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");

        Tanggal.setText(s.format(date));
        autonumber();
        // txtNoTransaksi.setText(autoNoTransaksi);
        Pembayaran.setText("0");
        ID_Customer.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ID_Customer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Customer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Tanggal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Qty = new javax.swing.JTextField();
        Tambah = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Kembalian = new javax.swing.JTextField();
        Pembayaran = new javax.swing.JTextField();
        Selesai = new javax.swing.JButton();
        TotalPembayaran = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        IdBarang = new javax.swing.JTextField();
        Harga = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Nama_Barang = new javax.swing.JTextField();
        Hapus = new javax.swing.JButton();
        Cari = new javax.swing.JButton();
        txtNo_Transaksi = new javax.swing.JTextField();
        Cari_Cutomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(100, 200));

        jPanel1.setBackground(new java.awt.Color(255, 51, 255));

        jLabel1.setBackground(new java.awt.Color(255, 0, 102));
        jLabel1.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KASIR INFOMART");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setDoubleBuffered(true);
        jLabel1.setFocusTraversalPolicyProvider(true);
        jLabel1.setName(""); // NOI18N
        jLabel1.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1150, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1150,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 103, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));

        jLabel1.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setText("No Transaksi");

        jLabel3.setText("ID Customer");

        ID_Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_CustomerActionPerformed(evt);
            }
        });

        jLabel4.setText("Customer");

        Customer.setEnabled(false);
        Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerActionPerformed(evt);
            }
        });

        jLabel5.setText("Tanggal");

        Tanggal.setEnabled(false);
        Tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalActionPerformed(evt);
            }
        });

        jLabel6.setText("ID Barang");

        jLabel7.setText("Qty");

        Qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QtyActionPerformed(evt);
            }
        });

        Tambah.setText("Tambah");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        jLabel8.setText("Pembayaran");

        jLabel10.setText("Kembalian");

        Kembalian.setEnabled(false);
        Kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembalianActionPerformed(evt);
            }
        });

        Pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PembayaranActionPerformed(evt);
            }
        });

        Selesai.setText("Selesai");
        Selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelesaiActionPerformed(evt);
            }
        });

        TotalPembayaran.setEnabled(false);
        TotalPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPembayaranActionPerformed(evt);
            }
        });

        jLabel11.setText("Total");

        Total.setBackground(new java.awt.Color(102, 102, 102));
        Total.setFont(new java.awt.Font("LED Dot-Matrix", 0, 55)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 255, 0));
        Total.setText("RP 0");
        Total.setDisabledTextColor(new java.awt.Color(255, 255, 51));
        Total.setEnabled(false);
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane2.setViewportView(jTable1);

        IdBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        IdBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdBarangActionPerformed(evt);
            }
        });

        Harga.setEnabled(false);
        Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaActionPerformed(evt);
            }
        });

        jLabel9.setText("Harga");

        jLabel12.setText("Nama Barang");

        Nama_Barang.setEnabled(false);
        Nama_Barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama_BarangActionPerformed(evt);
            }
        });

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        Cari.setText("Cari");
        Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariActionPerformed(evt);
            }
        });

        txtNo_Transaksi.setEnabled(false);
        txtNo_Transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNo_TransaksiActionPerformed(evt);
            }
        });

        Cari_Cutomer.setText("Cari");
        Cari_Cutomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cari_CutomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane2)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtNo_Transaksi,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 192,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(303, 303, 303)
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(Tanggal,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 193,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                                .createSequentialGroup()
                                                                .addComponent(Total,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 593,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(87, 87, 87)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(jLabel10)
                                                                                        .addGap(22, 22, 22)
                                                                                        .addComponent(Kembalian,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                197,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(jLabel11,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                66,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(TotalPembayaran,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                197,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(jLabel8)
                                                                                        .addGap(209, 209, 209))
                                                                                .addComponent(Pembayaran,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        197,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                        .addComponent(Selesai)
                                                                                        .addGap(90, 90, 90))))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                                .createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel4))
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(ID_Customer,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        193,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(Cari_Cutomer)
                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(Customer,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        193,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(0, 0,
                                                                                                        Short.MAX_VALUE))
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(IdBarang,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        105,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(Cari)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        Short.MAX_VALUE)
                                                                                                .addComponent(jLabel12)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(
                                                                                                        Nama_Barang,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        170,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jLabel9)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(Harga,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        170,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(jLabel7)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(Qty,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        170,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(Tambah)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(Hapus)
                                                                                                .addGap(15, 15, 15))))))
                                                        .addComponent(jLabel6,
                                                                javax.swing.GroupLayout.Alignment.LEADING))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5)
                                        .addComponent(Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNo_Transaksi, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(ID_Customer, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Cari_Cutomer))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(Customer, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel7)
                                                .addComponent(Qty, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Tambah)
                                                .addComponent(Hapus))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel9)
                                                .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel12)
                                                .addComponent(Nama_Barang, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel6)
                                                .addComponent(IdBarang, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Cari)))
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 142,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel11)
                                                        .addComponent(TotalPembayaran,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Pembayaran,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel10)
                                                        .addComponent(Kembalian, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(Selesai)))
                                .addGap(0, 0, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNo_TransaksiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNo_TransaksiActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNo_TransaksiActionPerformed

    private void Cari_CutomerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Cari_CutomerActionPerformed
        // TODO add your handling code here:
        Customer a = new Customer();
        a.setVisible(true);
    }// GEN-LAST:event_Cari_CutomerActionPerformed

    private void txtNo_Transaksi1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNo_Transaksi1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNo_Transaksi1ActionPerformed

    private void CariActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CariActionPerformed
        // TODO add your handling code here:
        ListDataBarang a = new ListDataBarang();
        a.setVisible(true);
    }// GEN-LAST:event_CariActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        model.removeRow(row);
        totalbiaya();
        Pembayaran.setText("0");
        Kembalian.setText("0");
    }// GEN-LAST:event_HapusActionPerformed

    private void IdBarangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_IdBarangActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_IdBarangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton1ActionPerformed

    private void HargaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_HargaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_HargaActionPerformed

    private void Nama_BarangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Nama_BarangActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_Nama_BarangActionPerformed

    private void TotalPembayaranActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TotalPembayaranActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TotalPembayaranActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TotalActionPerformed

    private void ID_CustomerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ID_CustomerActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_ID_CustomerActionPerformed

    private void CustomerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CustomerActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_CustomerActionPerformed

    private void NO_TransaksiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NO_TransaksiActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_NO_TransaksiActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1ActionPerformed

    private void QtyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_QtyActionPerformed
        // TODO add your handling code here:
        add();
    }// GEN-LAST:event_QtyActionPerformed

    private void KembalianActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_KembalianActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_KembalianActionPerformed

    private void PembayaranActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PembayaranActionPerformed
        // TODO add your handling code here:
        int total, bayar, kembalian;

        total = Integer.valueOf(TotalPembayaran.getText());
        bayar = Integer.valueOf(Pembayaran.getText());

        if (total > bayar) {
            JOptionPane.showMessageDialog(null, "Uang Tidak Cukup");
        } else {
            kembalian = bayar - total;
            this.Kembalian.setText(String.valueOf(kembalian));
        }
    }// GEN-LAST:event_PembayaranActionPerformed

    private void SelesaiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SelesaiActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        String NoTransaksi = txtNo_Transaksi.getText();
        String tanggal = Tanggal.getText();
        String idCustomer = ID_Customer.getText();
        String total = TotalPembayaran.getText();

        try {
            Connection c = koneksi.getkonesi();
            String sql = "INSERT INTO penjualan Values (?,?,?,?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, NoTransaksi);
            p.setString(2, tanggal);
            p.setString(3, idCustomer);
            p.setString(4, total);
            p.executeUpdate();
            p.close();
        } catch (Exception e) {
            System.out.println("Simpan Error");
        }

        try {
            Connection c = koneksi.getkonesi();
            int baris = jTable1.getRowCount();

            for (int i = 0; i < baris; i++) {
                String sql = "INSERT INTO rincipenjualan(No_Faktur, ID_Barang, Nama_Barang, Harga, Jumlah, Total) VALUES ('"
                        + jTable1.getValueAt(i, 0) + "','" + jTable1.getValueAt(i, 1) + "','" + jTable1.getValueAt(i, 2)
                        + "','" + jTable1.getValueAt(i, 3) + "','" + jTable1.getValueAt(i, 4) + "','"
                        + jTable1.getValueAt(i, 5) + "')";
                PreparedStatement p = c.prepareStatement(sql);
                p.executeUpdate();
                p.close();
            }
        } catch (Exception e) {
            System.out.println("Simpan Rinci Error");
        }
        hapus();
        utama();
        autonumber();
        kosong();
        Total.setText("RP 0");
    }// GEN-LAST:event_SelesaiActionPerformed

    private void TanggalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TanggalActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TanggalActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        add();
    }// GEN-LAST:event_TambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Project_Akhir.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Project_Akhir.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Project_Akhir.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Project_Akhir.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Project_Akhir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cari;
    private javax.swing.JButton Cari_Cutomer;
    public static javax.swing.JTextField Customer;
    private javax.swing.JButton Hapus;
    public static javax.swing.JTextField Harga;
    public static javax.swing.JTextField ID_Customer;
    public static javax.swing.JTextField IdBarang;
    private javax.swing.JTextField Kembalian;
    public static javax.swing.JTextField Nama_Barang;
    private javax.swing.JTextField Pembayaran;
    private javax.swing.JTextField Qty;
    private javax.swing.JButton Selesai;
    private javax.swing.JButton Tambah;
    private javax.swing.JTextField Tanggal;
    private javax.swing.JTextField Total;
    private javax.swing.JTextField TotalPembayaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtNo_Transaksi;
    // End of variables declaration//GEN-END:variables
}
